bin.includes = META-INF/,\
               lib/dagger-2.60.1.jar,\
               about_files/,\
               about.html
src.includes = lib/,\
               about_files/,\
               about.html
jars.compile.order = lib/dagger-2.60.1.jar
